// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Infrastructure;

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200504093232_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("WebApi.Infrastructure.Entities.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanetNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Trzecia, licząc od Słońca, oraz piąta pod względem wielkości planeta Układu Słonecznego.",
                            ImagePath = "assets/earth.jpg",
                            Name = "Ziemia",
                            PlanetNumber = 3
                        },
                        new
                        {
                            Id = 2,
                            Description = "Druga pod względem odległości od Słońca planeta Układu Słonecznego.",
                            ImagePath = "assets/venus.jpg",
                            Name = "Wenus",
                            PlanetNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Najmniejsza i najbliższa Słońca planeta Układu Słonecznego.",
                            ImagePath = "assets/mercury.jpg",
                            Name = "Merkury",
                            PlanetNumber = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ósma, najdalsza od Słońca planeta w Układzie Słonecznym, czwarta pod względem średnicy i trzecia pod względem masy",
                            ImagePath = "assets/neptune.jpg",
                            Name = "Neptun",
                            PlanetNumber = 8
                        },
                        new
                        {
                            Id = 5,
                            Description = "Czwarta od Słońca planeta Układu Słonecznego.",
                            ImagePath = "assets/mars.jpg",
                            Name = "Mars",
                            PlanetNumber = 4
                        },
                        new
                        {
                            Id = 6,
                            Description = "Piąta w kolejności od Słońca i największa planeta Układu Słonecznego",
                            ImagePath = "assets/jupiter.jpg",
                            Name = "Jowisz",
                            PlanetNumber = 5
                        },
                        new
                        {
                            Id = 7,
                            Description = "Szósta planeta Układu Słonecznego pod względem odległości od Słońca, druga po Jowiszu pod względem masy i wielkości",
                            ImagePath = "assets/saturn.jpg",
                            Name = "Saturn",
                            PlanetNumber = 6
                        },
                        new
                        {
                            Id = 8,
                            Description = "Siódma od Słońca planeta Układu Słonecznego, trzecia pod względem wielkości i czwarta pod względem masy.",
                            ImagePath = "assets/uranus.jpg",
                            Name = "Uran",
                            PlanetNumber = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
